<?php
// ================================================================
// LondonLab — Master Configuration (Auto-generated by installer) Sultan Ashraf
// ================================================================

define('MASTER_DB_HOST',    'localhost');
define('MASTER_DB_NAME',    'londonlab_master');
define('MASTER_DB_USER',    'londonlab_root');
define('MASTER_DB_PASS',    'Sultan@81');
define('MASTER_DB_CHARSET', 'utf8mb4');

define('PLATFORM_NAME',     'LondonLab');
define('PLATFORM_TAGLINE',  'Lab Management Software');
define('PLATFORM_URL',      'https://londonlab.in/londonlab');
define('SUPERADMIN_URL',    PLATFORM_URL . '/superadmin');
define('LAB_APP_URL',       PLATFORM_URL . '/lab_app');
define('BILLING_SUPPORT_EMAIL', 'billing@londonlab.in');

define('ROOT_PATH',         __DIR__ . '/..');
define('MASTER_PATH',       ROOT_PATH . '/master');
define('SUPERADMIN_PATH',   ROOT_PATH . '/superadmin');
define('LAB_APP_PATH',      ROOT_PATH . '/lab_app');
define('SQL_TEMPLATE_PATH', ROOT_PATH . '/master/sql/lab_template.sql');

define('TRIAL_DAYS',   14);
define('GST_PERCENT',  18);

date_default_timezone_set('Asia/Kolkata');
error_reporting(0);
ini_set('display_errors', 0);
// ================================================================
// MASTER DATABASE CLASS This Class is used to connect to the master database and perform queries. It uses the singleton pattern to ensure only one instance exists.
// ================================================================
class MasterDB {
    private static $instance = null;
    private $pdo;

    private function __construct() {
        $dsn = "mysql:host=" . MASTER_DB_HOST . ";dbname=" . MASTER_DB_NAME . ";charset=" . MASTER_DB_CHARSET;
        $this->pdo = new PDO($dsn, MASTER_DB_USER, MASTER_DB_PASS, [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false,
            PDO::ATTR_TIMEOUT            => 10,
        ]);
    }

    public static function getInstance(): MasterDB {
        if (!self::$instance) self::$instance = new MasterDB();
        return self::$instance;
    }

    public function getConnection(): PDO { return $this->pdo; }

    public function query(string $sql, array $params = []): PDOStatement {
        $stmt = $this->pdo->prepare($sql);
        $stmt->execute($params);
        return $stmt;
    }

    public function fetchAll(string $sql, array $p = []): array { return $this->query($sql,$p)->fetchAll(); }
    public function fetch(string $sql, array $p = []): ?array   { $r=$this->query($sql,$p)->fetch(); return $r?:null; }
    public function execute(string $sql, array $p = []): bool   { return $this->query($sql,$p)->rowCount()>0; }
    public function lastInsertId(): string                      { return $this->pdo->lastInsertId(); }
    public function beginTransaction(): void { if (!$this->pdo->inTransaction()) $this->pdo->beginTransaction(); }
    public function commit(): void           { if ($this->pdo->inTransaction()) $this->pdo->commit(); }
    public function rollback(): void         { if ($this->pdo->inTransaction()) $this->pdo->rollBack(); }
}

// ================================================================
// LAB DATABASE CLASS — connects to a specific lab's database
// ================================================================
class LabDB {
    private static $instances = [];
    private $pdo;

    private function __construct(string $dbName) {
        $dsn = "mysql:host=" . MASTER_DB_HOST . ";dbname=" . $dbName . ";charset=" . MASTER_DB_CHARSET;
        $this->pdo = new PDO($dsn, MASTER_DB_USER, MASTER_DB_PASS, [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false,
            PDO::ATTR_TIMEOUT            => 10,
        ]);
    }

    public static function getInstance(string $dbName): LabDB {
        if (!isset(self::$instances[$dbName])) {
            self::$instances[$dbName] = new LabDB($dbName);
        }
        return self::$instances[$dbName];
    }

    public function getConnection(): PDO { return $this->pdo; }
    public function query(string $sql, array $p = []): PDOStatement { $s=$this->pdo->prepare($sql); $s->execute($p); return $s; }
    public function fetchAll(string $sql, array $p = []): array { return $this->query($sql,$p)->fetchAll(); }
    public function fetch(string $sql, array $p = []): ?array   { $r=$this->query($sql,$p)->fetch(); return $r?:null; }
    public function execute(string $sql, array $p = []): bool   { return $this->query($sql,$p)->rowCount()>0; }
    public function lastInsertId(): string { return $this->pdo->lastInsertId(); }
    public function beginTransaction(): void { if (!$this->pdo->inTransaction()) $this->pdo->beginTransaction(); }
    public function commit(): void           { if ($this->pdo->inTransaction()) $this->pdo->commit(); }
    public function rollback(): void         { if ($this->pdo->inTransaction()) $this->pdo->rollBack(); }
}

// ================================================================
// LAB PROVISIONING — creates a new lab database
// ================================================================
class LabProvisioner {

    public static function provision(array $labData): array {
        $master = MasterDB::getInstance();

        // Generate slug and db name
        $slug   = self::generateSlug($labData['name']);
        $dbName = 'londonlab_' . $slug;

        // Check slug uniqueness
        $exists = $master->fetch("SELECT id FROM labs WHERE slug=? OR db_name=?", [$slug, $dbName]);
        if ($exists) {
            $slug   = $slug . '_' . rand(100,999);
            $dbName = 'londonlab_' . $slug;
        }

        $dbCreated = false;

        try {
            // 1. Create the lab database (separate DB — no master transaction needed here)
            $pdo = $master->getConnection();
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `$dbName` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $dbCreated = true;

            // 2. Run lab template SQL on the new database
            //    CRITICAL FIX: PDO::MYSQL_ATTR_MULTI_STATEMENTS must be TRUE
            //    because lab_template.sql contains many statements separated by ';'
            $labPdo = new PDO(
                "mysql:host=" . MASTER_DB_HOST . ";dbname=$dbName;charset=utf8mb4",
                MASTER_DB_USER, MASTER_DB_PASS,
                [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_TIMEOUT => 10,
                    PDO::MYSQL_ATTR_MULTI_STATEMENTS => true,
                ]
            );
            $sql = file_get_contents(SQL_TEMPLATE_PATH);
            if ($sql === false) {
                throw new Exception('Could not read lab_template.sql at ' . SQL_TEMPLATE_PATH);
            }
            $labPdo->exec($sql);

            // IMPORTANT: drain any remaining result sets left over from
            // multi-statement exec() — this is what causes the NEXT
            // prepared statement (INSERT INTO users) to hang forever
            // on some MySQL/PDO driver combinations (incl. XAMPP on Windows).
            while ($labPdo->getAttribute(PDO::ATTR_SERVER_INFO) !== null) {
                try {
                    $stmt = $labPdo->query('SELECT 1');
                    if ($stmt) { $stmt->closeCursor(); }
                } catch (Exception $e) {}
                break; // single drain pass is sufficient with PDO MySQL
            }

            // 3. Create the lab admin user in lab database
            $hashedPwd = password_hash($labData['password'], PASSWORD_DEFAULT);
            $userStmt = $labPdo->prepare("INSERT INTO users (name,email,password,role) VALUES (?,?,?,'admin')");
            $userStmt->execute([$labData['owner_name'], $labData['owner_email'], $hashedPwd]);

            // 4. Insert lab settings into lab database
            $labSettings = [
                ['lab_name',       $labData['name']],
                ['lab_address',    $labData['address'] ?? ''],
                ['lab_phone',      $labData['owner_phone'] ?? ''],
                ['lab_email',      $labData['owner_email']],
                ['lab_gstin',      $labData['gstin'] ?? ''],
                ['currency_symbol','₹'],
                ['report_footer',  'Results are for clinical guidance only. Consult your physician.'],
                ['order_prefix',   'ORD'],
            ];
            $settingsStmt = $labPdo->prepare("INSERT INTO settings (setting_key,setting_value) VALUES (?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)");
            foreach ($labSettings as $s) $settingsStmt->execute($s);

            // 5. Register lab in master database (only this part needs a transaction)
            $master->beginTransaction();
            $trialEnd = date('Y-m-d', strtotime('+' . TRIAL_DAYS . ' days'));
            $master->execute("
                INSERT INTO labs (name,slug,owner_name,owner_email,owner_phone,address,city,state,pincode,gstin,db_name,plan_id,status,trial_ends_at)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            ", [
                $labData['name'], $slug, $labData['owner_name'], $labData['owner_email'],
                $labData['owner_phone'] ?? '', $labData['address'] ?? '',
                $labData['city'] ?? '', $labData['state'] ?? '',
                $labData['pincode'] ?? '', $labData['gstin'] ?? '',
                $dbName, $labData['plan_id'] ?? 1, 'trial', $trialEnd
            ]);
            $labId = (int)$master->lastInsertId();
            $master->commit();

            return [
                'success'  => true,
                'lab_id'   => $labId,
                'slug'     => $slug,
                'db_name'  => $dbName,
                'trial_end'=> $trialEnd,
                'login_url'=> LAB_APP_URL . '/login.php?lab=' . $slug,
            ];

        } catch (Exception $e) {
            $master->rollback();
            // Try to drop the partially created database
            if ($dbCreated) {
                try { $master->getConnection()->exec("DROP DATABASE IF EXISTS `$dbName`"); } catch (Exception $e2) {}
            }
            return ['success' => false, 'message' => $e->getMessage()];
        }
    }

    private static function generateSlug(string $name): string {
        $slug = strtolower(trim($name));
        $slug = preg_replace('/[^a-z0-9]+/', '_', $slug);
        $slug = preg_replace('/_+/', '_', $slug);
        $slug = trim($slug, '_');
        return substr($slug, 0, 40);
    }
}

// ================================================================
// HELPERS
// ================================================================
function money(float $amount): string {
    return '₹' . number_format($amount, 2);
}

function clean(string $value): string {
    return htmlspecialchars(trim($value), ENT_QUOTES, 'UTF-8');
}

function timeAgo(string $datetime): string {
    $diff = time() - strtotime($datetime);
    if ($diff < 60)     return 'just now';
    if ($diff < 3600)   return floor($diff/60) . 'm ago';
    if ($diff < 86400)  return floor($diff/3600) . 'h ago';
    if ($diff < 604800) return floor($diff/86400) . 'd ago';
    return date('d M Y', strtotime($datetime));
}

function daysLeft(string $date): int {
    return max(0, (int)ceil((strtotime($date) - time()) / 86400));
}

function planBadgeColor(string $slug): string {
    return match($slug) {
        'basic'      => 'secondary',
        'pro'        => 'primary',
        'enterprise' => 'warning',
        default      => 'secondary'
    };
}

function statusBadgeColor(string $status): string {
    return match($status) {
        'trial'     => 'info',
        'active'    => 'success',
        'suspended' => 'warning',
        'cancelled' => 'danger',
        default     => 'secondary'
    };
}