<?php
// ================================================================
// LondonLab Install Wizard
// Run once to set up master database and super admin account
// DELETE this file after installation!
// ================================================================
session_start();

$step    = (int)($_GET['step'] ?? 1);
$errors  = [];
$success = false;

// ── STEP 2: Test DB connection ──
if ($step === 2 && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $host    = trim($_POST['db_host']    ?? 'localhost');
    $user    = trim($_POST['db_user']    ?? 'root');
    $pass    = trim($_POST['db_pass']    ?? '');
    $dbname  = trim($_POST['db_name']    ?? 'londonlab_master');
    $saName  = trim($_POST['sa_name']    ?? '');
    $saEmail = trim($_POST['sa_email']   ?? '');
    $saPwd   = trim($_POST['sa_password']?? '');
    $baseUrl = rtrim(trim($_POST['base_url'] ?? ''), '/');

    if (!$saName)  $errors[] = 'Super admin name is required.';
    if (!filter_var($saEmail, FILTER_VALIDATE_EMAIL)) $errors[] = 'Valid email required.';
    if (strlen($saPwd) < 6) $errors[] = 'Password must be at least 6 characters.';

    if (empty($errors)) {
        try {
            set_time_limit(300);

            // Connect without DB name first
            $pdo = new PDO("mysql:host=$host;charset=utf8mb4", $user, $pass, [
                PDO::ATTR_ERRMODE                => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_TIMEOUT                => 10,
                PDO::MYSQL_ATTR_MULTI_STATEMENTS => true,
            ]);

            // Create master database
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `$dbname` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $pdo->exec("USE `$dbname`");

            // Run master SQL
            $masterSql = file_get_contents(__DIR__ . '/../master/sql/master.sql');
            // Remove USE statement since we already selected DB
            $masterSql = preg_replace('/^USE\s+\w+;/mi', '', $masterSql);
            // Remove CREATE DATABASE statement
            $masterSql = preg_replace('/^CREATE DATABASE.*?;/mi', '', $masterSql);

            // Execute as one multi-statement batch (avoids per-statement
            // cursor hang seen with some PDO/MySQL driver combos)
            $stmtHandle = $pdo->prepare($masterSql);
            $stmtHandle->execute();
            do {
                // drain all result sets so the connection isn't left busy
            } while ($stmtHandle->nextRowset());

            // Create super admin (replace default)
            $hashedPwd = password_hash($saPwd, PASSWORD_DEFAULT);
            $pdo->exec("DELETE FROM super_admins");
            $pdo->prepare("INSERT INTO super_admins (name, email, password, role) VALUES (?, ?, ?, 'superadmin')")
                ->execute([$saName, $saEmail, $hashedPwd]);

            // Write config file
            $configContent = <<<PHP
<?php
// ================================================================
// LondonLab — Master Configuration (Auto-generated by installer)
// ================================================================
define('MASTER_DB_HOST',    '$host');
define('MASTER_DB_NAME',    '$dbname');
define('MASTER_DB_USER',    '$user');
define('MASTER_DB_PASS',    '$pass');
define('MASTER_DB_CHARSET', 'utf8mb4');

define('PLATFORM_NAME',     'LondonLab');
define('PLATFORM_TAGLINE',  'Lab Management Software');
define('PLATFORM_URL',      '$baseUrl');
define('SUPERADMIN_URL',    PLATFORM_URL . '/superadmin');
define('LAB_APP_URL',       PLATFORM_URL . '/lab_app');

define('ROOT_PATH',         __DIR__ . '/..');
define('MASTER_PATH',       ROOT_PATH . '/master');
define('SUPERADMIN_PATH',   ROOT_PATH . '/superadmin');
define('LAB_APP_PATH',      ROOT_PATH . '/lab_app');
define('SQL_TEMPLATE_PATH', ROOT_PATH . '/master/sql/lab_template.sql');

define('TRIAL_DAYS',   14);
define('GST_PERCENT',  18);

date_default_timezone_set('Asia/Kolkata');
error_reporting(0);
ini_set('display_errors', 0);
PHP;
            // Add rest of config (classes + helpers) from original
            $originalConfig = file_get_contents(__DIR__ . '/../master/config.php');
            // Extract everything after the define blocks (classes and functions)
            preg_match('/\/\/ ={64,}\n\/\/ MASTER DATABASE CLASS/s', $originalConfig, $match, PREG_OFFSET_CAPTURE);
            if (isset($match[0][1])) {
                $configContent .= "\n" . substr($originalConfig, $match[0][1]);
            }

            file_put_contents(__DIR__ . '/../master/config.php', $configContent);

            $_SESSION['install_success'] = true;
            $_SESSION['install_email']   = $saEmail;
            header('Location: ?step=3'); exit;

        } catch (PDOException $e) {
            $errors[] = 'Database error: ' . $e->getMessage();
        } catch (Exception $e) {
            $errors[] = 'Installation error: ' . $e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>LondonLab — Install Wizard</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
body{font-family:'DM Sans',sans-serif;background:#f5f3ff;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:30px 20px}
.install-wrap{max-width:680px;width:100%;background:#fff;border-radius:20px;box-shadow:0 20px 60px rgba(124,58,237,.12);overflow:hidden}
.install-head{background:linear-gradient(135deg,#1e1b4b,#7c3aed);color:#fff;padding:36px 40px;text-align:center}
.install-head .logo{width:64px;height:64px;background:rgba(255,255,255,.15);border-radius:16px;display:grid;place-items:center;font-size:30px;margin:0 auto 16px}
.install-head h1{font-size:26px;font-weight:700;margin-bottom:6px}
.install-head p{opacity:.7;font-size:14px}
.install-body{padding:36px 40px}
.step-bar{display:flex;gap:0;margin-bottom:32px}
.step-item{flex:1;text-align:center;position:relative}
.step-item::after{content:'';position:absolute;top:18px;left:50%;width:100%;height:2px;background:#e5e7eb;z-index:0}
.step-item:last-child::after{display:none}
.step-num{width:36px;height:36px;border-radius:50%;display:grid;place-items:center;font-weight:700;font-size:14px;margin:0 auto 6px;position:relative;z-index:1}
.step-item.done .step-num{background:#7c3aed;color:#fff}
.step-item.active .step-num{background:#7c3aed;color:#fff;box-shadow:0 0 0 4px rgba(124,58,237,.2)}
.step-item.pending .step-num{background:#e5e7eb;color:#9ca3af}
.step-label{font-size:11px;font-weight:600;color:#6b7280}
.form-label{font-size:13px;font-weight:600;color:#374151;margin-bottom:6px;display:block}
.form-control,.form-select{border:1.5px solid #e5e7eb;border-radius:10px;padding:11px 14px;font-size:14px;font-family:inherit;outline:none;width:100%;transition:border .2s}
.form-control:focus,.form-select:focus{border-color:#7c3aed;box-shadow:0 0 0 3px rgba(124,58,237,.1)}
.btn-install{background:#7c3aed;color:#fff;border:none;border-radius:10px;padding:13px 28px;font-size:15px;font-weight:600;font-family:inherit;cursor:pointer;transition:background .2s}
.btn-install:hover{background:#5b21b6}
.section-title{font-size:12px;font-weight:700;letter-spacing:.5px;text-transform:uppercase;color:#7c3aed;margin:20px 0 12px;padding-bottom:8px;border-bottom:2px solid #ede9fe}
.success-icon{width:80px;height:80px;background:#dcfce7;border-radius:50%;display:grid;place-items:center;font-size:36px;margin:0 auto 20px}
.info-box{background:#f5f3ff;border:1px solid #ddd6fe;border-radius:10px;padding:16px;font-size:13px;color:#5b21b6;margin-top:16px}
.info-box code{background:rgba(124,58,237,.1);padding:2px 6px;border-radius:4px;font-size:12px}
.warning-box{background:#fef3c7;border:1px solid #f59e0b;border-radius:10px;padding:14px;font-size:13px;color:#92400e;margin-top:16px}
</style>
</head>
<body>
<div class="install-wrap">
    <!-- Header -->
    <div class="install-head">
        <div class="logo"><i class="bi bi-activity"></i></div>
        <h1>LondonLab Install Wizard</h1>
        <p>Set up your Lab Management SaaS Platform</p>
    </div>

    <div class="install-body">
        <!-- Step Bar -->
        <div class="step-bar">
            <?php
            $steps = ['Welcome', 'Configure', 'Complete'];
            foreach ($steps as $i => $label):
                $num = $i + 1;
                $cls = $step > $num ? 'done' : ($step === $num ? 'active' : 'pending');
            ?>
            <div class="step-item <?= $cls ?>">
                <div class="step-num"><?= $cls === 'done' ? '✓' : $num ?></div>
                <div class="step-label"><?= $label ?></div>
            </div>
            <?php endforeach; ?>
        </div>

        <?php if ($step === 1): ?>
        <!-- STEP 1: Welcome -->
        <h4 class="fw-bold mb-2">Welcome to LondonLab! 🎉</h4>
        <p class="text-muted mb-4" style="font-size:14px;">This wizard will set up your platform in under 2 minutes. You'll need your MySQL database credentials ready.</p>

        <h6 class="section-title">Before You Begin</h6>
        <div class="d-flex flex-column gap-3 mb-4">
            <?php
            $checks = [
                ['PHP 8.0+',         phpversion() >= '8.0', 'PHP ' . phpversion()],
                ['PDO MySQL',         extension_loaded('pdo_mysql'), extension_loaded('pdo_mysql') ? 'Available' : 'Missing!'],
                ['MySQL access',      true, 'Will be verified in next step'],
                ['File write access', is_writable(__DIR__ . '/../master/'), is_writable(__DIR__ . '/../master/') ? 'Writable' : 'Not writable!'],
            ];
            foreach ($checks as [$label, $ok, $detail]): ?>
            <div class="d-flex align-items-center gap-3 p-3 rounded-2" style="background:<?= $ok?'#f0fdf4':'#fee2e2' ?>;">
                <i class="bi bi-<?= $ok?'check-circle-fill text-success':'x-circle-fill text-danger' ?> fs-5"></i>
                <div>
                    <div class="fw-semibold" style="font-size:14px;"><?= $label ?></div>
                    <small class="text-muted"><?= $detail ?></small>
                </div>
            </div>
            <?php endforeach; ?>
        </div>

        <a href="?step=2" class="btn-install">
            <i class="bi bi-arrow-right me-2"></i>Continue to Configuration
        </a>

        <?php elseif ($step === 2): ?>
        <!-- STEP 2: Configure -->
        <h4 class="fw-bold mb-1">Database & Admin Setup</h4>
        <p class="text-muted mb-4" style="font-size:14px;">Enter your database credentials and create the super admin account.</p>

        <?php if (!empty($errors)): ?>
        <div class="alert alert-danger mb-4">
            <ul class="mb-0"><?php foreach($errors as $e): ?><li><?= htmlspecialchars($e) ?></li><?php endforeach; ?></ul>
        </div>
        <?php endif; ?>

        <form method="POST">
            <h6 class="section-title">Database Configuration</h6>
            <div class="row g-3 mb-4">
                <div class="col-md-6">
                    <label class="form-label">DB Host</label>
                    <input type="text" name="db_host" class="form-control" value="<?= htmlspecialchars($_POST['db_host']??'localhost') ?>">
                </div>
                <div class="col-md-6">
                    <label class="form-label">Master DB Name</label>
                    <input type="text" name="db_name" class="form-control" value="<?= htmlspecialchars($_POST['db_name']??'londonlab_master') ?>">
                </div>
                <div class="col-md-6">
                    <label class="form-label">DB Username</label>
                    <input type="text" name="db_user" class="form-control" value="<?= htmlspecialchars($_POST['db_user']??'root') ?>">
                </div>
                <div class="col-md-6">
                    <label class="form-label">DB Password</label>
                    <input type="password" name="db_pass" class="form-control" placeholder="Leave blank if none">
                </div>
                <div class="col-12">
                    <label class="form-label">Platform Base URL</label>
                    <input type="text" name="base_url" class="form-control"
                           value="<?= htmlspecialchars($_POST['base_url'] ?? 'http://localhost/londonlab') ?>"
                           placeholder="http://yourdomain.com/londonlab">
                    <small class="text-muted">No trailing slash. Used for all internal links.</small>
                </div>
            </div>

            <h6 class="section-title">Super Admin Account</h6>
            <div class="row g-3">
                <div class="col-12">
                    <label class="form-label">Full Name</label>
                    <input type="text" name="sa_name" class="form-control" required
                           value="<?= htmlspecialchars($_POST['sa_name']??'') ?>" placeholder="Your name">
                </div>
                <div class="col-md-6">
                    <label class="form-label">Email</label>
                    <input type="email" name="sa_email" class="form-control" required
                           value="<?= htmlspecialchars($_POST['sa_email']??'') ?>" placeholder="admin@yourdomain.com">
                </div>
                <div class="col-md-6">
                    <label class="form-label">Password (min 6 chars)</label>
                    <input type="password" name="sa_password" class="form-control" required minlength="6">
                </div>
            </div>

            <div class="d-flex justify-content-between align-items-center mt-4">
                <a href="?step=1" class="btn btn-outline-secondary">← Back</a>
                <button type="submit" class="btn-install">
                    <i class="bi bi-database-fill-add me-2"></i>Install LondonLab
                </button>
            </div>
        </form>

        <?php elseif ($step === 3): ?>
        <!-- STEP 3: Success -->
        <div class="text-center">
            <div class="success-icon">🎉</div>
            <h4 class="fw-bold mb-2">Installation Complete!</h4>
            <p class="text-muted mb-4">LondonLab has been successfully installed. You're ready to go!</p>
        </div>

        <div class="info-box">
            <strong>🔑 Your Login Details</strong><br><br>
            Super Admin URL: <code><?= htmlspecialchars($_SESSION['install_email'] ?? '') ?></code><br>
            Email: <code><?= htmlspecialchars($_SESSION['install_email'] ?? '') ?></code><br><br>
            Access your admin panel at:<br>
            <code>http://your-domain/londonlab/superadmin/</code>
        </div>

        <div class="warning-box mt-3">
            <i class="bi bi-exclamation-triangle-fill me-2"></i>
            <strong>Security Warning:</strong> Delete this file immediately after installation!<br>
            <code><?= __FILE__ ?></code>
        </div>

        <div class="row g-3 mt-4">
            <div class="col-6">
                <a href="../superadmin/login.php" class="btn btn-primary w-100">
                    <i class="bi bi-shield-lock-fill me-2"></i>Go to Admin Panel
                </a>
            </div>
            <div class="col-6">
                <a href="../lab_app/login.php" class="btn btn-outline-primary w-100">
                    <i class="bi bi-box-arrow-in-right me-2"></i>Lab Login
                </a>
            </div>
        </div>
        <?php endif; ?>

    </div>
</div>
</body>
</html>